[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranberries-backend = { path = "../../lib/cranberries-backend" }

winit     = "0.20.0"
ash       = "0.33"
cgmath    = "0.17.0"
